### ISSUE TITLE
Group option to prevent an application from switching desktops

### ISSUE THREAD

**Issue by dvhx** [joewing/jwm#108]
I have following group settings:

&lt;Group>
  &lt;Name>chromium-browser&lt;/Name>
  &lt;Option>desktop:5&lt;/Option>
&lt;/Group>

Up until commit 4021c59 it worked as expected. But this commit introduced this code (client.c: line 418):

SetClientDesktop(np, currentDesktop);

Which brings active windows to current desktop regardless of group settings. It seems to do this whenever application state change so when my music player which is always on desktop 9 change track, it is brought to current desktop.

**Comment by joewing** [comment]
I think the solution here is to add another group option to either prevent an application from switching desktops or prevent it from switching desktops on raise.

**Comment by joewing** [comment]
As of snapshot 1431, there is a new group option, `fixed`, to keep the client on the specified desktop even when it is raised.  With this option, JWM will change to the desktop with the window rather than moving the window.  This probably doesn't completely address this issue, but it may help in some cases.

**Comment by joewing** [comment]
The `fixed` option addresses this issue for me, so I'm marking this as closed.
