### ISSUE TITLE
Dock's transparency is not working when using compositor.

### ISSUE THREAD

**Issue by Donskoy-tabak** [joewing/jwm#130]
I found one annoying bug: when compositing manager(compton/xcompmgr/etc) and dock(plank/cairo-dock/docky/etc) active simultaneously, instead transpancy area it have black background. This trouble also actual for icewm and uwm. In other wm like openbox, fluxbox, xfwm4, etc docks works fine.

JWM 2.2.2

I noticed that this bug is relevant in wm with integrated taskbar panel. Maybe this bug is in the stack of the taskbar or smth alike.

Icewm bugreport with the same bug:
http://sourceforge.net/p/icewm/mailman/icewm-devel/thread/From_noreply@sourceforge.net_Wed_Feb_27_18:10:15_2013/

Screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/6958041/3944149/0b50627a-25ee-11e4-92bb-b426351b2969.png)

Thanks!

**Comment by joewing** [comment]
From what I can tell, the problem is that JWM is reparenting the window.  These windows do not appear to be setting _NET_WM_WINDOW_OPACITY on the top-level window.   I think the correct way to fix this is to avoid reparenting windows that don't want a border or title bar.  Unfortunately, this is going to take a bit of development effort to make work.
