### ISSUE TITLE
Problem with menus in Matlab

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#139]
It has been reported to me that there is a problem with menus in Matlab under JWM.  The menus display for a brief time (sometimes) and disappear.  Matlab appears to have a Java front end.

**Comment by joewing** [comment]
Unfortunately, I no longer have easy access to Matlab.
If anyone knows of another program that demonstrates this behavior, please let me know.

**Comment by bbidulock** [comment]
I heard that tabbed rxvt is behaving like Java.  It appears to be with regard to focus behavior.  Both Java an tabbex rxvt appear to have a focus "coordinating" child window that passes focus to a non-subordinate subwindow under the same client.  If you don't look at all focus change events for the client window in detail, window managers can easily think that the focus has changed to the client, when it is really changing between child window trees under the client and mistakenly pass focus to the client.  The client windows appear to set both accepting input focus as well as being given focus, and if focus is passed to the client directly, the menu loses focus and drops; whereas, if the WM_TAKE_FOCUS protocol is used instead, things work out ok, or, sometimes the other way around.  Java misbehaves in these cases (behaves the opposite of tabbed rxvt), so either one breaks or the other.  Some WM's have resorted to detecting the name of the Java child focus "coordinator" to determine which way to go for Java clients.

Another difficulty with some clients with regard to menus is that they map menus as toplevel windows of the popup type without setting override redirect on the the window, and then steal focus.  Some focus logic in the WM can refuse to give focus to the new toplevel because there was no click (in click to focus model), or at the end of a restack procedure because a different window is still supposed to have focus.  Because the menu toplevel loses focus, it drops.

Both problems can cause the briefly-appearing, self-dropping menu effect.

A proper toolkit (GTK, Qt, Fox, Fltk, even Xt) will always map its menus as toplevel windows with override redirect set and will grab focus and will hold it until the appropriate key or a button is pressed.

**Comment by joewing** [comment]
I don't know if this still happens and I have no way to reproduce it, so I'm closing this.  If this still happens, I would be interested to hear about it, preferably with an application that I can use for  testing.
