### ISSUE TITLE
Better handling of .desktop Exec= commands

### ISSUE THREAD

**Issue by technosaurus** [joewing/jwm#149]
.desktop files can contain various entries with %<char> that will fail to execute as specified
http://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables
My current  automatic menu generation method just strips all of them out; however, most menu generators don't do this.

If these were removed in RunCommand() it would improve compatibility with other menu generators and open up the possibility of later implementing XDND to fill the %* with dragged file or text selections.
One thing to be cautious of though is to only remove the .desktop only specifiers like %f and %U (not just %*), so-as to not break shell commands with printf

**Comment by Israel-** [comment]
Hi, after doing a lot of testing, and programming, and building of jwmrc files I think the thing that would be most useful is if the Traybutton could be extended to have some type of action associated with dragging a file over it.  Basically if the file mimetype is 'text/plain' and you drop it over a tray button with xedit then the filename is added to exec:xedit.
You could 'turn this on' by using this:
<TrayButton icon="geany.png">exec:geany %f</TrayButton>
and then a quick grep of the desktop file for the mime type of the file and it opens.
otherwise it simply ignores it since you are not clicking it.

**Comment by joewing** [comment]
I opened a new issue to add XDND support to tray buttons (issue #170).
Any extra support for .desktop files is something I think is best handled outside of JWM.
