### ISSUE TITLE
"Cant focus" window's attribute does not work.

### ISSUE THREAD

**Issue by Donskoy-tabak** [joewing/jwm#151]
For example, gtk_window_set_accept_focus (GTK_WINDOW(window), FALSE) does not work in JWM. This attribute actually is necessary for some applications or something like that.

**Comment by joewing** [comment]
As @bbidulock mentioned, to ensure you don’t get input, it’s necessary to clear to do more than set WM_TAKE_FOCUS.  WM_TAKE_FOCUS tells the window manager that the application will assign focus, but it doesn’t prohibit the window manager from doing so.  Some window managers probably don’t assign focus when WM_TAKE_FOCUS is set (only sending a client message to the window).  Currently, JWM both sends the client message and sets the focus to the window when WM_TAKE_FOCUS is set.  JWM does it this way primarily because I don’t trust applications to handle WM_TAKE_FOCUS correctly.  Though, maybe that’s not really an issue.

In any case, to actually prevent a window from getting input focus, you can set input=False in the WMHints structure on the window.  JWM will still highlight the window, but it will send keyboard events to the root window (to discard them).

All this has me thinking that perhaps JWM should highlight the window that actually has input focus rather than the window JWM wants to have input focus, and then only send the client message.

**Comment by joewing** [comment]
After thinking about this some more, I've decided to leave it as is.  I think the real complaint here is likely that the window border is marked active even if the window does not take input (any application that really depended on not getting input focus is probably broken, so this is just cosmetic).  However, even if an application itself does not want input focus, JWM needs some way to indicate that any key bindings (such as close or maximize) are going to go to the window, which it does my marking the window active.  Of course, if you don't want JWM to manage the window at all there are other options (override_redirect for one).
I'm not familiar enough with openbox, etc. to know how they handle the situation.
