### ISSUE TITLE
Question..re: autohide tray

### ISSUE THREAD

**Issue by pevsner** [joewing/jwm#162]
The last couple of times I built and tried jwm, I couldn't get autohide to work (the tray is ever present).
I see you have added the ability to have several trays and change locations which is cool.
autohide="true" (I tried ="yes",="1" etc to no avail) doesn't seem to work, what is the command please? The example.jwmrc didn't shed any light or my perusal of other code.
Thanks.

**Comment by tone77** [comment]
autohide="true" is ok.
After you must run in the shell the following command 
jwm -restart
or
Menu -> Shutdown -> Restart JWM

**Comment by pevsner** [comment]
Ok thanks tone77, I'm pretty sure I did a restart. I'll rebuild and give it another go.

**Comment by joewing** [comment]
The configuration of autohide has changed recently (see http://joewing.net/projects/jwm/release-2.3.shtml for a list of changes since the last release).
As of commit d0a8032ad5dcf37b2d22cc01e3126bf0c9bc2697, you need to specify where the tray hides ("left", "right", "top", "bottom", or "off") rather than just "true" or "false".

**Comment by pevsner** [comment]
Thx Joe,
I hadn't seen the release notes, as I just "pull" from git usually.
Will check it now.
