### ISSUE TITLE
Gradient on dock doesn't work

### ISSUE THREAD

**Issue by solarboogie** [joewing/jwm#164]
I'm really enjoying JWM, getting it looking really good now,
One issue I have found is that when I am using a gradient for the background tray style, all the other tray components follow suit beautifully except the dock, which fills itself with a solid colour, the colour being the final value of the gradient.
I'm using the latest source with all options enabled.
Btw did you know the JWM in Ubuntu 14.04 repositories doesn't have .svg support enabled? I don't know why not.

**Comment by Israel-** [comment]
Hi,
I talked with the Debian package maintainer about updating JWM.  The Ubuntu version is something around 2.1.0.  Not only is it missing svg support, but it is also missing jpeg support.
The Debian maintainer said he would update it when 2.3.0 came out.  I also gave him the correct packaging files to include svg support, jpeg support and a few other things (dh-autoreconf for one).

Ubuntu gets all their packages from Debian, unless someone spends a ton of time trying to get the newest version in, for each release.  But it is much better for Debian packages to come through rather than Ubuntu only modifications.

**Comment by joewing** [comment]
Gradients don’t work in the dock because JWM doesn’t control the background of dock items (it’s a similar situation with swallowed applications in the tray).  I’m not aware of a way around this, unfortunately.

**Comment by joewing** [comment]
Assuming there isn't a way around this, I'm closing this issue.  Please re-open if I am mistaken.  I would be interested to see how this is done if another window manager or dock application has the ability to show gradients (or some arbitrary background) behind dock icons.
