### ISSUE TITLE
ConfigureRequests for maximized windows

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#175]
Before commit 460bc3cec9da0c94303a99d79a30ef91d1566105, JWM would unmaximize a maximized window if a ConfigureRequest was received for that window to change its size.  This causes problems with some applications. such as lxterminal.  lxterminal will send a ConfigureRequest after it is maximized causing it to be unmaximized.  Commit 460bc3cec9da0c94303a99d79a30ef91d1566105 changed it so JWM would ignore the request.

Ideally, it should be possible for JWM to respect the request either by restoring the old behavior or by unmaximizing the window and then maximizing it again.  In the lxterminal case, there might be something more going on.  Unmaximizing and maximizing the window causes the window to have the wrong size when it is unmaximized by the user.

**Comment by bbidulock** [comment]
I checked a recent lxterminal and it is horrible.  Other vte-based terminals use gtk2 or gtk3, but it looks like lxterminal is using xcb directly, and doing a poor job of it.  I used to be a heavy lxterminal user, but had so many problems with it that I converted over to roxterm, which is quite superior.  I don't know about making the WM fix the app: the app would never get fixed if we continue fixing its bugs in the window manager.

**Comment by joewing** [comment]
I don't know how to make all the applications happy, so I'm going to leave this as is (with lxterminal, etc. broken).

**Comment by wdlkmpx** [comment]
Well, JWM is almost there. I think you should reconsider your position hehe...

I think this behavior is somehow caused by the VTE library.

The VTE sample app and the Sakura Terminal Emulator both behave just like LXTerminal.

This issue is solved in Openbox and Icewm, there might some comments in the source code of those projects regarding this tricky situation, maybe a hack, a workarournd, something like that.
