### ISSUE TITLE
RootMenu label doesn't work

### ISSUE THREAD

**Issue by limelime** [joewing/jwm#186]
I set the label attribute of RootMenu in /root/.jwmrc as follows:
```
....
   <RootMenu label="Start" ...>
...
```
After restarting JWM, it still show 'JWM'.

I'm using Debian with JWM vsvn-579.

**Comment by Israel-** [comment]
Hi this is working in at least git version 1102 and up... possibly earlier
You may also want to modify
```xml
<TrayButton label="JWM">root:1</TrayButton>
```

**Comment by limelime** [comment]
thx Israel, TrayButton is what I need.

**Comment by Israel-** [comment]
Glad it worked for you!!  If you want to try a different menu system, (if you are using the Debian menu/menu-xdg packages) that builds from the desktop files (/usr/share/applications) rather than the menu files I have a script I adapted from Puppy Linux.  I use it in Ubuntu, so it should work just the same in Debian ( I have also used it manually in Fedora).  You simply:
`# apt-get install menu menu-xdg xdg-user-dirs-gtk xdg-user-dirs xdg-utils`
And browse this:
http://bazaar.launchpad.net/~israeldahl/jwm-menu/trunk/files
you can use bzr to branch it:
`bzr branch lp:jwm-menu`
cd into the directory and (if not root run sudo)
```
cp etc/menu-methods/toriOSmenu etc/menu-methods
cp etc/menu-methods/places etc/menu-methods
cp -R usr/share/desktop-directories/ usr/share/
```
```xml
<Include>$HOME/.config/torimenu</Include>
<!-- snip-->
<TrayButton label="Apps" icon="distributor-logo.png" border="false">root:5</TrayButton>
```
For a Places menu use:
```xml
<Include>$HOME/.config/placesmenu</Include>
<!-- snip-->
<TrayButton label="Places" icon="folder.png" border="false">root:7</TrayButton>
```
