### ISSUE TITLE
Disable all icons for windows (in titlebar and taskbar)

### ISSUE THREAD

**Issue by aleksandr-samusenko** [joewing/jwm#187]
I dont need ever icon for window - neither in window's title, nor in taskbar. Some commits ago it was possible by this setting for group "all windows classes" ("\<Class\>^\</Class\>"): "\<Option\>icon:\</Option\>" (empty string for icon), but now this "hack" doesn't work...

May be, it possible to restore such behaviour? How?

**Comment by yetanothergeek** [comment]
Maybe try:
```xml
<Option>icon:/dev/null</Option>
```

**Comment by joewing** [comment]
JWM used to try to load the window icon from the window itself and then override it with an icon specified via a group option.  I figured it was inefficient to try to load the icon twice, so now JWM attempts to load from a group option and only if that fails load from the window itself.  Of course, JWM doesn't check to see if there is a group icon specified or not, only that an icon was loaded.  So if an icon wasn't loaded due to the icon not being found, JWM will often still load an icon.

A possible work around would be to point JWM at a transparent png.  In general, I think supporting "icon:" as a special case is probably the way to go.

**Comment by joewing** [comment]
This should work as before (with "icon:" giving no icon) as of snapshot 1145.

**Comment by aleksandr-samusenko** [comment]
Yes, now the icons OK - they are absent ) Thanks.
