### ISSUE TITLE
Port to XCB

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#194]
I come across with this in the other day not sure if it interests you but i will drop the link here!
https://en.wikipedia.org/wiki/XCB

**Comment by technosaurus** [comment]
I started writing some notes to support this a while back:
https://github.com/technosaurus/jwm/commits/master
I was only trying to learn xcb though, at the time xcb was missing a few
things that have since been completed.
Even still it is an undertaking that would only benefit threading since
any size benefit can be had by compiling against musl libc and
https://github.com/idunham/tinyxlib
Making jwm multithreaded would increase the code complexity/size.
Unfortunately libX11 is not going away any time soon
(gtk still has't finished their xcb port)
Doing this now is just premature optimization.
Feel free to fork jwm and try it, if you are just interested in learning xcb
or look at http://uwm.sourceforge.net/
However, time would be better spent finishing the gtk port or
fixing the decade+ old bug in libX11 that nearly doubles its size for
no useful purpose (namely including its own iconv)

**Comment by joewing** [comment]
I don't know that there would be much to gain from switching to libxcb.  As mentioned, JWM is not multithreaded and probably wouldn't benefit much from being multithreaded.  More importantly, libxcb would be an additional dependency to be ported to platforms where JWM currently runs with ease (old versions of Solaris, IRIX, HP-UX, AIX, etc.).

**Comment by vmnlopes** [comment]
@joewing @technosaurus i only dropped the link here since i read that it has performance benefits compared with libx11 and jwm is good with that, anyway C his out of my league just wanted joe to be aware of XBC also i read some applications are porting to it.
