### ISSUE TITLE
Plugin support

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#197]
for  example:  
```javascript
< Script type="bash" > getent passwd $USER | cut -d ':' -f 5 | cut -d ',' -f 1 < /Script >
```
and get the output of the script displayed in the tray or a menu.

The example script above displays the user name output = Joe Wing

you can start with bash and in the future add support for other languages?

example:
```javascript
< Script type="python" > print("my script") < /Script >
< Script type="php"> echo "my script"; < /Script >
< Script type="javascript">/path/to/my/script/jwm_rocks.js < /Script>
```

this his fairly easy to implement in python have no idea how it works in C.

Also it might be a good idea to implement the path for the language!

example:  <ScriptPath Type="php">/usr/bin/php</ScriptPath>

**Comment by joewing** [comment]
The examples aren't showing up for me...

**Comment by vmnlopes** [comment]
fixed github wont show tags if i dont leave a space just after <

**Comment by yetanothergeek** [comment]
> *fixed github wont show tags if i dont leave a space just after* <

Or you could write it this way:
```XML
<Script type="python" > print("my script") </Script>
<Script type="php"> echo "my script"; </Script >
<Script type="javascript">/path/to/my/script/jwm_rocks.js </Script>
```
( Click the ["Markdown supported"](https://guides.github.com/features/mastering-markdown/) link above the edit box for more tricks. )

**Comment by vmnlopes** [comment]
@yetanothergeek 

nice one thanks for the tip

**Comment by technosaurus** [comment]
I wonder if the new "dynamic" tag could be used

**Comment by Israel-** [comment]
I think this begs to include Joe's own language....  Will JL be supported soon?  If not adding in support for Plugins via some exposed API in the code would be great with bindings for other languages like Python etc... personally I would much rather have a script based interface that can be used (using Bash/sh/zsh/whatever).  I like scripting languages because it can combine many different things, and scripting is extremely good for certain applications where doing something in C is much more difficult (for example sed,grep,awk, bash arrays from ls, etc...).  And scripts are easy to modify for the end user, modifying a compiled language is much more intensive.

And exposed API would be nice, but even a simple zenity/gxmessage/xmessage/yad/gtkdialog/(etc..)-like shell scripting interface would be extremely versitile.

@joewing  Maybe simply making doxygen page of the JWM code would help some of us who are interested in playing with ideas but very unfamiliar with the codebase have a way into JWM?

**Comment by vmnlopes** [comment]
@technosaurus the "dynamic" tag is not working for me but the "command" tag works like a charm its just a shame only works in the desktop tag.

**Comment by technosaurus** [comment]
After looking at the dynamic tag, this is great ... Now I don't have to bother with a daemon for updating a menu and doing a -reload just to modify a disk browser menu.  Adding the exec: to include would only happen when the xml is parsed.  My menu generator is fast enough to do them on the fly, so this is great.

I'll have to see what happens if I use it to add all the closing tags for the parent menu then a tray button or something to test followed by a dummy menu header to pair up with the closing ones.

**Comment by joewing** [comment]
Allowing customization like this was my motivation for creating a s-expression based language to replace the XML configuration (JL).  I think that's the direction I would like this to go, but that's a fairly significant change.

I used to generate doxygen documentation for JWM.  I'll look into getting that going again.

**Comment by Israel-** [comment]
Yes, please do the doxygen thing again!!!
Also please provide a more comprehensive explanation for JL, I looked at it a week or so ago, but if this is something that is a way off, just keep in mind I am the type of user that requires detailed documentation as you may already have guessed from my semi-frequent queries about new features.
Which reminds me, what is the timeout period for the dynamic tag.  It seems if I have a script that takes too long it will not work (and sometimes render JWM unresponsive). I am sure I could write something quicker if I did it in C or something, but I like having a non-binary menu.  The new JWM system doesn't require icon extentions, so that will cut down on a lot of the processing time as well.

**Comment by joewing** [comment]
There will certainly need to be more information around JL if/when JWM switches to it.

As far as the dynamic menus are concerned, there currently isn't a time out, but there really should be.  I'll add one and make it configurable

**Comment by joewing** [comment]
I created a new issue for the dynamic menu timeout (issue #203).

**Comment by joewing** [comment]
Doxygen documentation is back: http://joewing.net/projects/jwm/doc/

**Comment by Israel-** [comment]
thanks @joewing

**Comment by vmnlopes** [comment]
@joewing I am unfamiliar with s-expressions did a bit of googling and came across with lisp that I am also unfamiliar can you give a short example how (JL) syntax will look like?

**Comment by Israel-** [comment]
Check this out
http://www.joewing.net/projects/jl/index.shtml

**Comment by vmnlopes** [comment]
@Israel- tanks i had a look its a bit alien to me.

@joewing any chance you can support xml configuration also or you completing changing over to (JL)?
in my opinion seems a bit 2 much having to learn a new language to do a simple configuration that way it will narrow down the ability to configure  to developers only!

**Comment by joewing** [comment]
Ideally JWM would only support the new language.  I was thinking it would be possible to have a parser written in JL that interpreted XML, (or perhaps just a program to do the conversion).

The new configuration would be somewhat similar to the current one for basic configurations, just with a slightly different syntax.  For example, a menu might look like this in the current configuration:

```xml
<Menu icon="folder" label="Apps">
  <Program icon="term_icon" label="My Terminal">xterm</Program>
</Menu>
```

With s-expressions, that would turn into something like:
```lisp
(menu (icon "folder") (label "apps")
  (program (icon "term_icon") (label "My Terminal") (exec "xterm"))
)
```

Of course, the advantage to having this as a program language is that you could define and use functions, etc.  In any case, I think this change is probably pretty far off.

**Comment by vmnlopes** [comment]
@joewing your example seems easy to pick up i like it creates a standard.

i was brainstorming about this today.

and i come up with another approach execute configuration file the same way we execute stuff in linux.

.jwmrc contents example.

```javascript
#!/usr/bin/env python  OR  #!/usr/bin/bash

import os.path
print('''<?xml version="1.0"?>
<JWM>    
     <Menu icon="folder" label="Apps">
  <Program icon="term_icon" label="My Terminal">xterm</Program>
</Menu>
</JWM>''')
```
OR
```javascript
#!/usr/bin/jl      # joe S-Expressions (JL)

(menu (icon "folder") (label "apps")
  (program (icon "term_icon") (label "My Terminal") (exec "xterm"))
)
```
OR spiting some (JL) in python

```javascript
#!/usr/bin/env python  OR  #!/usr/bin/bash

import os.path
print(" (menu (icon 'folder') (label 'apps')")
print("  (program (icon 'term_icon') /(label 'My Terminal') /(exec 'xterm'))")
print(")")

```
This will cause more fragmentation but at the same time also more freedom of choice and the ability to do anything in any language.

Will leave the idea here marinating.

**Comment by Israel-** [comment]
You can use eval_gettext in shell scripts... so potentially you could use the same sort of thing.... but then again xgettext only works for certain languages

**Comment by joewing** [comment]
As of #291, JWM finally supports running scripts via the `Include` tag, which I think solves a lot of this issue.  The rest is probably best left until a more radical change (switching to JL, for example).
