### ISSUE TITLE
Lag dragging GTK3 windows

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#208]
Most people use JWM in low end machines i use it in a quad core with 8gb ram i was using gtk2 apps
and in the other day i decided to start migrating to gtk3 and dragging applications windows  lags really bad i shif the mouse arrow to the other corner of the screen and the window starts moving when the arrow actualy gets there,

I think this is related with the way gtk3 implements client side window decorations, although when i use compton the the situation improves but it still lags behind, actualy feeling more sluggish that with gnome desktop.

i use opensource video drivers!

Any way to fix this?

**Comment by joewing** [comment]
One of the machines I use for testing JWM is a SPARCstation IPX with an 80 MHz processor and 64 MB of RAM (maxed out!).  Obviously Gtk3 is pretty much a non-starter on such a machine, but it seems to handle things fine (opaque moving/resizing).
One thing that can slow things down is the status window displayed when moving windows.  Since this window is typically on top of the window being moved, it can cause the window to be redrawn when moved.  You can disable the status window by setting:
```xml
<MoveMode coordinates="off">opaque</MoveMode>
```
You can do the same for ResizeMode, but resizing typically requires a redraw anyway.
JWM sets the save-under flag for these status windows, but the X server is allowed to ignore that.

Another thing JWM does is attempt to discard mouse motion events when there are multiple in the queue, but I suppose it could be more aggressive at this.

**Comment by joewing** [comment]
The performance should be a little better now as of snapshot 1231.  JWM was double buffering the whole frame, but really it only needs to double buffer the title bar, so that's what it does now.

**Comment by vmnlopes** [comment]
@joewing this did not work for me!
```javascript
<MoveMode coordinates="off">opaque</MoveMode>
<MoveMode coordinates="off" delay="1">opaque</MoveMode>
```
at the moment i only got version 2.3.1 in the repos but will setup a virtual machine to test snapshots in the future.

**Comment by vmnlopes** [comment]
@joewing snapshot 1233 does not have any lag at all brilliant am closing this!
