### ISSUE TITLE
Logout: Issues

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#212]
sometimes when login out using the exit tag the trays and window decorations disappear but the desktop keeps running!

using Lightdm not tested with others?

**Comment by joewing** [comment]
JWM doesn't really control logout.  It's just another X client.  Typically, the display manager or X11 startup scripts run the window manager directly, and then cause a log out when the window manager exits.

Is JWM still running when this happens?

**Comment by vmnlopes** [comment]
@joewing i lose control over the open windows only the one on the top remains usable, not shure if it is still running but next time it happens i will do (ctrl + alt + f2) and have look!

**Comment by vmnlopes** [comment]
@joewing it happen today again did top and jwm is still running when i do killall jwm, the cpu shots to 100% any ideas?

ps - it seams it only happens when i leave the pc on for long periods of time!

**Comment by joewing** [comment]
Strange, I don't recall seeing anything like this. Was JWM using 100% CPU or was a different process?

When this happens, would it be possible to attach gdb to get a stack trace ("gdb attach <pid>" where <pid> is the PID of JWM)?  Once in gdb, type "bt" to get the stack trace.

**Comment by Israel-** [comment]
@vmnlopes it might be useful to also know your distro (Ubuntu/Debian/Fedora/Arch/LFS/etc....), and what version of JWM you are using/where you got it (is it compiled from the latest Git, a PPA, or.....)

**Comment by vmnlopes** [comment]
@joewing 

JWM 2.3.1.2 from the repository.
Manjaro linux
Kernel 4.1

sorry i seam i do not to have any command called gdb am not familiar how to get the stack trace can you possibly give me detailed instructions please.

**Comment by vmnlopes** [comment]
@joewing I was unfamiliar with gdb but managed to get the output hope this helps.

top output:
```javascript
PID USER      PR  NI    VIRT    RES  %CPU %MEM     TIME+ S COMMAND
1939 vmnlopes    20   0  247.2m  18.7m 100.0  0.3   2:05.24 R jwm
```
gdb output:
```javascript
#0  0x00007f37e33b16db in _XReply () from /usr/lib/libX11.so.6
#1  0x00007f37e33a75a9 in XQueryExtension () from /usr/lib/libX11.so.6
#2  0x00007f37e339b352 in XInitExtension () from /usr/lib/libX11.so.6
#3  0x00007f37e1ecc38f in XextAddDisplay () from /usr/lib/libXext.so.6
#4  0x00007f37e1ec6732 in ?? () from /usr/lib/libXext.so.6
#5  0x00007f37e33b3a61 in _XEnq () from /usr/lib/libX11.so.6
#6  0x00007f37e33b086f in ?? () from /usr/lib/libX11.so.6
#7  0x00007f37e33b1830 in _XReply () from /usr/lib/libX11.so.6
#8  0x00007f37e33ad11d in XSync () from /usr/lib/libX11.so.6
#9  0x00007f37e338ec78 in XCloseDisplay () from /usr/lib/libX11.so.6
#10 0x0000000000405686 in ?? ()
#11 0x00007f37e192f610 in __libc_start_main () from /usr/lib/libc.so.6
#12 0x0000000000405729 in ?? ()
Detaching from program: /usr/bin/jwm, process 1939
```

**Comment by joewing** [comment]
That's a somewhat strange stack trace in that gdb was unable to find functions to line up with a few of the frames.  Not too surprising though if JWM was stripped, I suppose.  In any case, assuming the stack trace is accurate, JWM is trying to close its connection to the X server (the XCloseDisplay call).  One of the things XCloseDisplay does is call XSync to flush any errors back to the client, so that seems reasonable.

What I don't understand is why XCloseDisplay would be hanging.  It almost certainly shouldn't be hanging.  It could be trying to report an error back to JWM and JWM isn't responding, but it doesn't appear to be doing that and JWM doesn't do anything in the error handler anyway for a non-debug build.  It could also be an issue with JWM stomping on memory, but that typically manifests in different ways (and there are lots of checks in JWM to prevent that).

So it looks to me like either a bug in the X server or an extension.  A debug build of JWM might provide some additional information, but if it's indeed hanging in XCloseDisplay, I don't know what to do about it.  I suppose another thing to check would be running xrestop to see if JWM is leaking resources (though that really shouldn't cause a hang either).

**Comment by vmnlopes** [comment]
@joewing compiled a debug build from snapshot 1233 if this happens again what do i do to debug, use gdb or do something else?

**Comment by joewing** [comment]
If it happens again, gdb is probably the best thing to do.

**Comment by vmnlopes** [comment]
@joewing I wen i do jwm -p i get a memory leak report
```javascript
DEBUG: main.c[114]: debug mode started
DEBUG: main.c[242]: debug mode stopped
DEBUG: MEMORY: memory leaks follow
DEBUG:         58 bytes in misc.c at line 222
DEBUG:         64 bytes in misc.c at line 222
DEBUG:         56 bytes in misc.c at line 222
DEBUG:         56 bytes in misc.c at line 222
DEBUG: MEMORY: 4 memory leaks

**Comment by joewing** [comment]
Would you be able to post your configuration (or at least enough of it to reproduce the memory leaks)?

**Comment by joewing** [comment]
Never mind, I think I found it!

**Comment by joewing** [comment]
I fixed one memory leak when running 'jwm -p' (available in snapshot 1240).  That particular issue was due to JWM not cleaning up completely when only parsing the configuration, so it wouldn't happen when running normally.  Because it only happens with "-p", it's not serious, but it should be fixed now.  There may be other similar issues, I'll keep looking.

**Comment by vmnlopes** [comment]
closing this one is not happening on snapshot 1233
