### ISSUE TITLE
Tags cleanup?

### ISSUE THREAD

**Issue by cicku** [joewing/jwm#226]
Hi,

I see hundreds of tags migrated from SVN, is it time to remove them? You should keep stable versions there.

Thanks.

**Comment by joewing** [comment]
I probably should clean those up.  Every time I create a "snapshot", I create a tag.  The tags can be useful if someone reports a bug in an old snapshot, but I would like to avoid that situation in general, especially for the really old versions.  So I may just remove all the "s#" tags at some point.

**Comment by Israel-** [comment]
I like having tags, as I used them for my JWM PPA to merge with upstream.
Otherwise I will have to download the repo manually and merge it manually... as it is, I simply type in 1 command `bzr merge-upstream` and everything is done automatically.
:)
But, you can delete older ones.  just keep a good amount around for tracking issues/regressions

**Comment by joewing** [comment]
I just deleted a bunch of old tags.  Going forward, I think I may try to delete tags after each new release.

Creating the snapshot tags is fairly easy to do, so if I was too aggressive in deleting tags, they can always be re-generated.
