### ISSUE TITLE
Some icons missings of the dock

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#231]
by default use 22 height to tray. but when increasing (for example 23 height) some icons missings of the dock. see images:

- 22 height 
http://www.auplod.com/u/olpdua664e0.png

- 23 height
http://www.auplod.com/u/udpola664e1.png

i need to do "Ctrl - r" (jwm -restart) 3 or 4 times in order to see all the icons of the dock.

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
some discussions:

http://polr.me/4b3
http://polr.me/4b4
http://polr.me/4b5

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
some icons are outside of the tray when I run $ jwm -restart.

http://bit.ly/1MEAZ2r

perhaps related to this issue...

vlw fwi, Holmes :)

**Comment by technosaurus** [comment]
@holmeslinux Why don't you just drag the image to the comment box (it will auto upload and insert a link)  instead of using a link that requires a user account to view... Who really trusts shortened URLs anyhow?

**Comment by Israel-** [comment]
@holmeslinux also, your image for 23 has:
`<!-- Tray at the bottom -->`
but you clearly are using
`valign="top"`

that said, I have experienced some oddities in the Dock lately too.  I was testing Dropbox's dock icon and it drew the battery (or wireless depending on where it positioned) behind itself.
The battery would also occasionally disappear when suspending.

But the battery usually reappears after I hover over it.
I wonder if your
`cbatticon -u 120 -i standard -c "systemctl suspend" -l 20 -r 5`
is the issue?
Once systemd took over power management (rather than just upower) things had to be rewritten and changed.  It may be that the battery program does not refresh quickly enough?
I think the refresh 3 or 4 times is a coincidence of timing.  I could be totally off, but it is a thought.  Contact the cbatticon maintainer and see if it is a bug there

**Comment by joewing** [comment]
I think this may have the same cause as issue as #238.  If so, it should be fixed as of snapshot 1299.

**Comment by joewing** [comment]
Please re-open if this is still an issue.

**Comment by jerefeltan** [comment]
Now, in jwm 2.3.4, the icons do not disappear. But very often, when I run `jwm -restart` some icons are outside of the Dock (previously mentioned) http://bit.ly/1MEAZ2r
I think this issue should be re-opened.

**Comment by joewing** [comment]
I think I’m able to reproduce this (not sure, as like @technosaurus I don’t really trust shortened URLs and refuse to follow them).  I opened issue #260 to track the issue.
