### ISSUE TITLE
buttons in about dialog

### ISSUE THREAD

**Issue by simargl** [joewing/jwm#240]
In about dialogs JWM has two buttons in title: maximize and close. I suggest to have buttons for minimize and close, that is to remove maximize because it doesn't work anyway.

~ $ jwm -v      
JWM v2.3.2 by Joe Wingbermuehle
compiled options: confirm fribidi icons jpeg nls png shape svg xbm xft xinerama xpm xrender 
system configuration: /etc/system.jwmrc

**Comment by joewing** [comment]
I assume this relates to about dialogs in applications such as GIMP.  For GIMP, the window has the following property set:
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DIALOG
So JWM could disable maximize for such windows.

**Comment by joewing** [comment]
Actually, it occurs to me that a better solution might be to disable maximize if the program-specified maximum size is the same as the program-specified minimum size.

**Comment by simargl** [comment]
![untitled](https://cloud.githubusercontent.com/assets/11329609/11019744/5727b336-8607-11e5-8c8f-eca69d685ef8.png)
I switched to jwm from openbox because of two reasons mainly, first addition of dynamic menus and second it seems in more active development, but there are stiill some things that was not good and maybe could be fixed.
So what is not okay (for me ) in this screen shot
1. application chooser dialog icon uses fallback icon, I think it should have same icon as its main application ( for comparison there is how that dialog looks in openbox https://lkubaski.files.wordpress.com/2012/10/xpad.png?w=630)
2. fallback icon is not that good, X suggests that something is broken, square icon like this could be better
https://github.com/danakj/openbox/blob/master/data/openbox.png
3. terminal window has black colored outline on top, but not on left side, Dialog does not have outline at all. and seems that's because JWM shows border only if window size exceeds some specified value in pixels.

**Comment by Israel-** [comment]
First off, @simargl you have a very nice setup for your window style, well done!

He makes a good point, the red color and it being an X suggests something is wrong.  If it were a blue and white square the user might not think something was broken.
Or, if @joewing decided to use the ribbon JWM as the fallback (with more gentle colors than red) I think that would also be fine as a fallback.  Perhaps, not drawing an icon would be sufficient?

perhaps, looking first for some generic icon in the user's <IconPath> would be good enough?

**Comment by joewing** [comment]
@simargl, thanks for the feed back!
As of snapshot 1318:
* JWM no longer makes maximize available if max-size == min-size.  Minimize is hidden because some applications will not accept input if a dialog is shown (so minimizing it could cause a confusing situation).  I'm somewhat on the fence about that though.
* JWM uses the icon from the owner if a transient window doesn't specify a window.

For the fall-back icon, I think the thing to do is to introduce an option to set the default icon and replace it with a square or a circle or something simple that would match the window border.

As far as the border issue is concerned, I don't seem to have that problem.  However, I think there is a bug in some X servers that causes them to do strange things when using X primitives to draw directly to windows, which is how JWM renders window outlines.  It's a shame because that doing so allows JWM to go much faster and use less memory... but I may have to work around it (double buffer writes).  What version of X11/pixman are you using (the output of ```X -version```).  Also, are you using a compositor such as compton or xcompmgr?

**Comment by technosaurus** [comment]
If you build jwm from source,  you can provide a different image in src/x.xpm
There are quite a few other defaults that you can manually set too.

**Comment by simargl** [comment]
*What version of X11/pixman are you using (the output of X -version).*
~ $ X -version

X.Org X Server 1.17.4
Release Date: 2015-10-28
X Protocol Version 11, Revision 0
....
Current version of pixman: 0.33.4

*Also, are you using a compositor such as compton or xcompmgr?*
Yes, xcompmgr, and indeed If I disable compositor all window outlines become visible.

**Comment by simargl** [comment]
Compiled latest version of jwm from git and changes are okay, thanks, Although when suggesting square icon I thought you would just convert openbox icon from that link to xpm and use it as replacement.

**Comment by joewing** [comment]
I didn't want to just take an icon for a few reasons:
* I would have to select a size/color combination, which is something I didn't like about the old X logo icon. 
* As with the old X logo icon, if XPM (or XBM, depending on the type of icon used) icons are disabled, you don't get an icon.
* I don't want to take use someone else's work without their explicit permission (and I would prefer to have something specific to JWM).

Of course, the "square" is kind of boring.  I think making a configurable default would be desirable.  I opened issue #246 for this.

**Comment by technosaurus** [comment]
Is there a way to make an icon to center instead of upscale.  indexed png, xpm and xbm icons tend  look horrible when scaled by small increments.

FWIW, I converted the entire Public Domain Tango Icon Set to indexed png and xpm icons (also released Public Domain with some indexed color icons added)  I should really put them up on github since the freedesktop.org host has lost most of it.
The Icon naming specification really needs to be updated to add these icons specifically, but I was using process-close, view-fullscreen and button-min for the window close, max and min buttons (respectively)

FWIW the spec hasn't been updated in almost a decade and is missing other icons like "applications-education" even though it is a recommended main category in the menu spec.
For one reason or another my messages to the mailing list never get through though and it is no longer possible to edit the wiki unless you get an account which also seems to have issues.
