### ISSUE TITLE
Lazy evaluation of dynamic menu items

### ISSUE THREAD

**Issue by LastOfBrunnenG** [joewing/jwm#244]
JWM is sometimes used on old machines. Evaluating 'dynamic' menu items each time root menu gets activated might be a problem. It might cause an interruption, sort of jerky performance. Perhaps 'dynamics' might be evaluated only after parent container gets activated. IceWM seems to be working that way.

How could lazy evaluation help ? One might create a sub menu and put dynamic entry inside it. If it gets evaluated only when parent sub menu gets activated, one should experience no interruption in other branches of root menu.

It is not a big issue. I have replaced 'Dynamic' entry with a 'program' entry labeled 'refresh'. It creates a file which gets included using 'include' tag.

**Comment by technosaurus** [comment]
This should not be a problem unless you are using something like java to do the dynamic parts.  I wrote a menu generator that parses all of the .desktop files in /usr/share/applications, complete with localization, that executes on an old pentium in <0.2s.

FWIW the menu generator that puppy was using at the time was written in C and was 20x slower, but no, I'm not saying that shell script is faster than C.

See http://www.murga-linux.com/puppy/viewtopic.php?t=70238 for some good tips.

Basically, avoid making external calls to sed, grep, awk, etc... when there is a way to do it with shell builtins because the elf dynamic loading overhead far outweighs the benefits of using external utilities 99% of the time.

I have quite a few that would be useful to put up on github once I update them to the current state (or perhaps add a ./contrib directory to jwm's repo?).

Here is an example (busybox ash) script that I wrote for use as the StartupCommand
(Note the lack of any external commands - only shell builtins) 
<pre><code>#!/bin/ash

matchDeskEnv(){
   ret=1; IFS=";"
   for Env in ${1}; do
      case ":${XDG_CURRENT_DESKTOP}:" in
         *":${Env}:"*)ret=0;break;;
      esac
   done
   return $ret
}

doDesktopFile(){
   EXEC="";EXECPATH="";BACK=$PWD
   while read LINE; do
      case "$LINE" in
         Exec=*)EXEC=${LINE#*=};;
         Path=*)EXECPATH=${LINE#*=};;
         Hidden=true*)return;;
         OnlyShowIn=*)matchDeskEnv ${LINE#*=} || return;;
         NotShowIn=*)matchDeskEnv ${LINE#*=} && return;;
      esac
   done < $1
   [ "$EXECPATH" ] && cd $EXECPATH
   [ "$EXEC" ] && $EXEC &
   [ "$EXECPATH" ] && cd $BACK
}

AUTOSTARTDIR=${XDG_CONFIG_HOME:-${HOME}/.config/}/autostart
for Entry in ${AUTOSTARTDIR}/*.desktop; do
   doDesktopFile $Entry
done

IFS=":"
for DIR in ${XDG_CONFIG_DIRS:-/etc/xdg}; do
   for Entry in ${DIR}/autostart/*.desktop; do
      #allow users to block/override system settings
      [ -f "${AUTOSTARTDIR}/${Entry##*/}" ] && continue
      [ -f "${Entry}" ] && doDesktopFile $Entry
   done
done 
</code></pre>

FWIW, I rewrote many of the old hotplug scripts using these same guidelines and they outperformed udev.
