### ISSUE TITLE
Title center window in JWM

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#274]
hi guys, i wonder if it is possible to center the title of the window.

vlw fwi, Holmes :)

**Comment by joewing** [comment]
This should be fairly easy to implement.  It would add another configuration option (maybe an attribute on the `Font` element for `WindowStyle`).

**Comment by holmeslinux** [comment]
hi Joe, if it is easy could implement this feature?

thx Joe...

vlw fwi, :)

**Comment by blconde** [comment]
This would be nice, (I guess I'll talk the obvious, anyway) and also to place the window titles to the right, because this could give more possibilities to design a JWM theme (I remember I like a some Openbox and/or Xfce themes with the window titles placed right).

And is there a jwm-look.org or some kind of JWM themes repository?

**Comment by Israel-** [comment]
@blconde there are only a few distros that use JWM as the default DE, and With most of the configurations, we have our own ways of doing things.
For instance 
```
 <Key key="XF86AudioMute">exec:amixer-toggle</Key>
    <Key key="XF86AudioRaiseVolume">exec:amixer-up</Key>
    <Key key="XF86AudioLowerVolume">exec:amixer-down</Key>
    <Key key="XF86MonBrightnessUp">exec:torios-gamma up</Key>
    <Key key="XF86MonBrightnessDown">exec:torios-gamma down</Key>
    <Key key="Print">exec:screenie</Key>
    <Key mask="CA" key="p">exec:screenie</Key>
    <Key mask="S4" key="3">exec:screenie</Key>
```
Would be useless in most instances, as only ToriOS has the scripts referenced.  And the scripts are complex enough that a single bash -c "#whatever" would make the configuration too complicated to maintain well.
You can also make JWM `<Include>` other files, which Puppy does and this further complicates the transfer to other computers.  Also, JWM does not support the freedesktop Icon standard, so If you use my .jwmrc and do not have Numix-Circle installed you will have a very different desktop.

So to make a theme, I would have to include all the binaries
```
    <RootMenu onroot="2">
        <Include>exec:/usr/bin/jwm-menu</Include>
        <!-- MENUS -->
      </RootMenu>
    <RootMenu onroot="7">
        <Include>exec:/usr/bin/jwm-places</Include>
    </RootMenu>
```
AND all the specific programs we use in our distro.
There is no standard Network Tray app (Puppy has their own in house, we use NetworkManager, and you can also use WICD though I suggest changing the icons)
There is no standard powermanager, or volume, or......
So the complications of sharing themes becomes exponential.
Also, earlier versions of JWM require much different things, like endings to Icon names, i.e.
reload.svg
instead of
reload
There are many other changes that make portability a problem.

In ToriOS (as well as in Puppy, and perhaps the others) we offer multiple themes, and ways to create your own theme easily (no XML required).
Puppy is vastly different from ToriOS, but the target userbase is also different and both have their really good qualities (I for one have always loved Puppy)

I hope my response is not too long winded, but explains the issue well enough.

**Comment by blconde** [comment]
At least to me, I believe it's better to talk more than to talk less, but mainly: very nice to know about ToriOS! Sure would be nice to follow the project.
I'm gonna try it any time soon (is it loaded with JWM snap 1369 by default?), I guess could be a well deserved upgrade to my still running Lubuntu 12.04.

As well, I'd like to show the project I'm collaborating a little: Manjaro JWM, https://forum.manjaro.org/index.php?topic=29323.0 . It's headed just by Holmes, and here you can take a look at the dev thread for the next version (where most of the questions asked here applied): https://forum.manjaro.org/index.php?topic=30486.0 . Be welcome to take a look, and I hope this exchange can be very nice to both projects.

*

Finally, let's keep doing what we're doing: giving feedback to Joe, trying the new features, maybe  a few suggestions (trying to get the "hands dirt" and writing some code lines? Ehehe), anyway, maintained the JWM community up and active.

**Comment by holmeslinux** [comment]
ToriOS or not the focus is known about the possibility of centering the title in the windows.

vlw fwi, Holmes :)

**Comment by joewing** [comment]
Thanks to @roandbox, this is available as of snapshot 1380.
