### ISSUE TITLE
Logout in oblogout ask confimation

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#275]
hi all,
i'm having doubts about the logout command in oblogout.

=> menu have: `<Exit label="Logout" confirm="false"/>` and does not ask confirmation.
=> oblogout have: `jwm -exit` and ask for confirmation.

image here https://forum.manjaro.org/index.php?topic=30486.msg252430#msg252430, ask for conformation!

i would like to know how to avoid confirmation.

vlw fwi, Holmes

**Comment by roandbox** [comment]
It  works :
> => menu have: <Exit label="Logout" confirm="false"/> and does not ask confirmation.
> => oblogout have: jwm -exit and ask for confirmation.> 

Please write a version of JWM.

**Comment by Israel-** [comment]
I set this in a non used menu JUST for this purpose
```
<RootMenu height="0" onroot="z">
        <Exit label="Logout" confirm="false" icon="system-logout.svg"/>
    </RootMenu>
```
This works for me.
It has worked since Joe implemented a-z menus
I didn't use it before, so I cannot tell if it worked before.
`pkill -u $USER` is not a really nice way to do things IMO, but it is your distro :)
If you guys want an example of a working fully functional jwmrc
You can check the ToriOS version
http://bazaar.launchpad.net/~torios-dev/torios/trunk/view/head:/etc/skel/.jwmrc
This has a full set of key bindings that are compliant with most GNU/OSX/Windows key bindings.
We also have a bunch of scripts to do a lot of the work for our users, such as icon theme generation, volume control (using amixer) we have scripts to generate menus, but we also have binary programs for the applications, and 'places' menus.  It might be good to collaborate at some point if you are interested.

**Comment by holmeslinux** [comment]
hi guys, my idea is to add the `jwm -exit` in oblogout.  however, I would like to remove the confirmation of JWM: 
**
Exit JWM
Are you sure?
OK Cancel**

how to remove the Exit in oblogout?

ps: version JWM = 2.3.4.

vlw fwi, Holmes :)

**Comment by joewing** [comment]
The way JWM currently works is somewhat broken.  The exit confirmation is a global setting even though it appears that it can be configured on a per-item basis in the configuration file.  To fix this, JWM should treat it as configuration for each instance of "Exit" (or "Restart") in the configuration.  Also, JWM should never show an exit confirmation when "-exit" is invoked from the command line.

**Comment by joewing** [comment]
This should be fixed in snapshot 1370.

**Comment by holmeslinux** [comment]
thank you Joe and i hope it can be resolved in the next version!

vlw fwi, Holmes :)
