### ISSUE TITLE
Customizable menu border

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#31]
Currently the color of menu borders is computed based on the background color of the menu.  This request is to allow that color to be customizable.
My proposal is to make the "Outline" tag in "MenuStyle" specify the menu border color (currently it specifies the color of the active item) and add "ActiveOutline" to specify the color of the active item.  The color in "Outline" or "ActiveOutline" could be extended to support two colors separated by a colon so that the top/left border could be a different color than the bottom/left border.

**Comment by joewing** [comment]
Added in revision 49033a5a.

**Comment by Israel-** [comment]
This fix has now made borders on all my buttons, previously I had flat buttons.
How do I get my previous look and feel back?  The newest configuration changes (removing tasklist style, etc....) do not have as detailed information as I'd like :)

**Comment by joewing** [comment]
I'm still trying to decide out how it should work. I tried making it flat, but I actually liked the old way better with the 3d look.  The computed collors are nice too (I haven't actually run into a case where I wanted something else).  So I'm trying to make it as simple as possible to configure without taking away too much flexibility.

**Comment by Israel-** [comment]
@joewing the top panel is fine looking, though I liked the flat buttons better, so an option to remove the border would be nice.
This is especially noticeable in my side panel that has icons only.  It looks not so nice now, mainly because I use Numix-Circle icons which are all circular (as you can guess).  So the squared boxes around the circles makes it look like more Win95/Gnome1ish... If you can implement some attribute like:
```xml
<Tray button="flat"></Tray>
```
where 'button' can be 'flat' or 'raised' and the default is 'raised' (or whatever) so no attribute is needed for the default behavior that would be fine for me.
