### ISSUE TITLE
Change license?

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#320]
It has been suggested that JWM adopt a less restrictive license, such as the simplified BSD license or ISC.  I’m open to suggestions, of course.

**Comment by technosaurus** [comment]
+1 for me.  (All of my patches are released to Public Domain)

jwm is my last holdout to have a basic linux subsystem with a basic Xserver, wm and terminal that I could compile into a single MIT/X licensed multicall binary (I statically compile against musl-libc and tinyX11).  It significantly reduces the binary sizes to the point where I can now put everything needed to boot to a desktop in a 1MB onboard flash (perfect for coreboot, a.k.a. linux bios)

An MIT/X11 compatible license would be awesome for use in the base system because versions of the GPL are incompatible with each other and could prevent a GPL3 program from being included in one of these multicall binaries if it already has GPLv2 only stuff .... Then there is android with the no GPL in userspace rule - it would be nice to have a _good_ window manager available for android.

 I have been trying to learn xcb to write my own replacement for this purpose (using libxcb, stb-image and nanosvg)... but xcb is not that much of an improvement over Xlib (aside from async) - it still doesn't just take a pointer to a struct for request data, so the function prototypes are still stupidly long, painful to write and contribute ~half of the library size.

**Comment by joewing** [comment]
The way I see it, changing the license is only a benefit for end users and I don’t imagine any contributors really care.  I think I’m going to go with the ISC license since it’s simple.

**Comment by technosaurus** [comment]
Sounds great.  It may even make jwm a candidate for the default wm for some of the BSDs where ISC is preferred.

**Comment by dumblob** [comment]
I would advocate for MIT as it's proven by huge projects like Fedora (if I'm not mistaken, Fedora guys even use MIT to globally relicense public domain works, because otherwise problems occur).

If I expect not only individuals to use my software for their own non-profit purposes, I stick to principles mentioned in https://www.youtube.com/watch?v=-bAAlPXB2-c (keynote about licenses from the GitHub co-founder) and look at http://choosealicense.com/ to choose a globally legally respected and globally legally-proved-to-be-ok license.

ISC (in contrast to e.g. MIT) assumes [Berne convention](https://en.wikipedia.org/wiki/Berne_Convention) applies, but in many countries in the world Berne convention is not ratified and thus the ISC license will prevent users and companies in these countries from using JWM and external users/companies from doing any related business (e.g. importing any products containing JWM) into those countries.

**Comment by joewing** [comment]
Given that ISC and MIT are so similar, I’m fine with using MIT instead.  My original pick of ISC was based on its simplicity, but MIT is fairly simple as well, and much more common.
