### ISSUE TITLE
gimp's icon in the task list being stretched

### ISSUE THREAD

**Issue by nixingizgood** [joewing/jwm#328]
hi, this is what my task list looks like with gimp...

![tl](https://cloud.githubusercontent.com/assets/15900066/18482271/52962880-7994-11e6-8b42-5f79711b52b2.png)

a wide, blurry stretched out icon. I'm attaching the gimp project so you can check it yourself.

[tl.zip](https://github.com/joewing/jwm/files/470303/tl.zip)

**Comment by joewing** [comment]
The issue here is that Gimp sets its icon to the image being manipulated.  JWM then scales the image to the appropriate height and maintains its aspect ratio.  So if you have a really wide image, this will happen.  I guess the solution is to have JWM limit the max width of the icon (probably to the max height of the icon).

**Comment by nixingizgood** [comment]
I'd rather the gimp logo be preserved from when the app starts. I see no use in having a miniature preview on the task list.

**Comment by joewing** [comment]
Well, neither do I.  Unfortunately, that's what GIMP provides, you'd have to take that up with the GIMP maintainers.
