### ISSUE TITLE
Tray buttons flat and TaskList buttons with shape?

### ISSUE THREAD

**Issue by fredvs** [joewing/jwm#330]
Hello.

First of all, congratulation for your marvelous JWM.
It is used for [polYdev](https://github.com/fredvs/polYdev), a FreeBSD disto. 

Is it possible, with last release, to have all the Tray-buttons flat (without shape) and the buttons of TaskList with shape ?

I have try but I get or all (Tray and Task buttons) flat or all shaped.

Many thanks.

Fre;D

**Comment by joewing** [comment]
It's not currently possible, but it should be pretty easy to add.  The configuration would probably look something like this:
```xml
<TrayStyle decorations="flat">
 ...
</TrayStyle>
<TaskListStyle decorations="motif">
...
</TaskListStyle>
```

**Comment by kafran** [comment]
I vote for this =)

**Comment by technosaurus** [comment]
I'm still trying to figure out where/how to modify the tray and button code  to accept a "none" background color.

IIRC There was an enhancement issue to support background images for trays, but it may not be useful unless the other enhancement issue requesting individual properties for each tray/button because an image that scales well vertically, may not scale well vertically.

This would allow us to use buttons as desktop icons when there's a desktop background image or gradient color.  We can already do it with flat background colors.   xvesa + jwm with a black background and tray buttons with a matching background as the "desktop icons" only uses ~4Mb of RAM ... Perfect for a doccer image.

**Comment by joewing** [comment]
This issue is certainly on my near-term to-do list.

@technosaurus Making the background of a tray transparent will either require the use of the composite extension or pseudo-transparency (which is just re-drawing the background of the root window translated to fit the tray).  I would lean toward using pseudo-transparency since that’s probably easier and more in-line with the portable and light-weight nature of JWM.  In either case, it’s not a trivial change.

The tray background image issue is #40.  I don’t think this issue is related though, since this is about the the decorations (borders really).

**Comment by joewing** [comment]
This is available as of snapshot 1559.

**Comment by fredvs** [comment]
Many thanks Joe !

**Comment by fredvs** [comment]
Wow, you added all the parameters for  <TaskListStyle> (not only decorations).

So I was able to custom active-inactive background for TaskList only.

Well done and many thanks.

PS: To compile JWM on FreeBSD, `automake -a` did not work but using:

`autogen.sh + configure + make + strip` => works like charm, out of the box.

Fre;D
