### ISSUE TITLE
Enhancement: extend support for the urgent hint by blinking miniature windows

### ISSUE THREAD

**Issue by dumblob** [joewing/jwm#345]
The urgent hint as described in https://github.com/joewing/jwm/issues/91 and https://github.com/joewing/jwm/issues/25 currently changes color of the task bar entry. It would be nice to also make the corresponding miniature window in the desktop switcher blink (switch foreground and background color periodically e.g. each 500 ms).

**Comment by joewing** [comment]
This should be pretty simple to do.  I could have sworn it already supported this, but it appears not.

**Comment by joewing** [comment]
This appears to work for me (I must have missed it in the code when I looked before, but it's certainly supported).  Perhaps you're using an older version of JWM?

**Comment by dumblob** [comment]
Hm, I didn't check the code yet, but I still can't achieve any blinking :cry:. Few minutes ago I downloaded and packaged the recent master branch of this GitHub repository and tested it with the upstream config file (see the screenshot below) as well as with my config file. In both cases the miniatures don't blink. I'm testing it in Xephyr. See the screenshot below.

![2016-12-20-113404_1680x1050 0 0_imlib2_grab](https://cloud.githubusercontent.com/assets/2451044/21347397/b49af5f4-c6a8-11e6-9203-d3020f6694f2.png)

Do you have any ideas what and how to test it more thoroughly?

**Comment by joewing** [comment]
Here’s the code that does it: https://github.com/joewing/jwm/blob/master/src/pager.c#L684
It works for me and the window border flashes as well.  If the active window has the urgency hint set, it doesn’t flash, maybe that’s what you’re seeing?

**Comment by dumblob** [comment]
Hi @joewing, let me apologize for the delay (live is sometimes a bit unpredictable...).

Well, you're right, the task list record and window border flashes. Having active windows with the urgency hint set not blink seems weird - I would expect it to blink all the time until the window (i.e. the application) itself decides to remove the urgency hint (that's at least my understanding of [ICCCM](https://tronche.com/gui/x/icccm/sec-4.html ) chapter *4.1.2.4. WM_HINTS Property*). Or at least blink all the time in the task bar if the border blinking of an **active** window would seem too obtrusive.

But overall the setting and unsetting of the "urgency" hint seems somehow not reliable for me (I'm using the latest git version of JWM). For example I could not achieve to have two windows to have the urgency hint set, but just one. Does JWM implement the behavior described in https://www.reddit.com/r/archlinux/comments/tbj6w/setting_wm_urgent_hint/c4ojcbr/ (i.e. the root window takes care of it and if I'm not mistaken, JWM controls the root window)?

**Comment by joewing** [comment]
It seems strange to me that an active window would have the urgent hint set.  What is the application that’s doing this?  Most I’ve used clear the urgency hint when they get focus.  My interpretation of the urgency hint is to bring the users attention to a window that may not be focused or on the current desktop.  Once the window has focus, it has you’re attention and it’s up to the client to direct your attention appropriately.

JWM supports either using ICCCM or EWMH to set the urgency hint.  Having multiple windows with the urgency hint set shouldn’t be a problem (I’m able to get a full desktop of blinking xterms).  The root window doesn’t need to be involved (if you use ICCCM).  With EWMH, the client just sends a client message to root to inform the window manager of the state change.  The full state must be reflected in NET_WM_STATE, so the “demands attention” needs to be set each time the client updates its state if it is to remain urgent.  Having a third-party client set the urgency hint would probably be unreliable since the client would almost certainly clear the urgency hint every time it updated its state.

**Comment by dumblob** [comment]
>What is the application that’s doing this?

Applications using a tabbed interface - can be a web browser, rxvt, etc. Some of them do not jump directly to the first "urgent" tab once the window gets focus and therefore they're waiting with the urgent hint set until the user focuses/unshades all "urgent" tabs.

>Having a third-party client set the urgency hint would probably be unreliable since the client would almost certainly clear the urgency hint every time it updated its state.

I've tested it again with this in mind and you're absolutely right - I've been setting the urgent hint externally and the applications were effectively removing it. Thank you very much for the explanation and sorry for the fuss (I didn't read the whole EWMH chapter, but only ICCCM and it was a mistake).

This issue is solved (blinking works for me).
