### ISSUE TITLE
Enhancement: Define default opening coordinates

### ISSUE THREAD

**Issue by J-Reis** [joewing/jwm#348]
I think it would be useful (for myself certainly and hopefully to others), if the <group> tag could be used to define starting coordinates for a given application or at least to start them aligned to the left|right side of the screen. Default size of the window on opening would be nice too. Allowing one to create a sort of default tiling layout for applications commonly used together.

**Comment by joewing** [comment]
This looks like #79.  Might want to add `width` and `height` parameters.

A potential problem with `height` and `width` is deciding whether they should be in pixels or the increments that the window specifies.  I lean toward pixels (and fix up as necessary to make fit the increments), since that would allow terminals and other applications, for example, to share the same window group.

**Comment by joewing** [comment]
The x, y, width, and height group options are available as of snapshot 1572.
