### ISSUE TITLE
Centralize/nolist script python window

### ISSUE THREAD

**Issue by holmeslinux** [joewing/jwm#352]
hi all,
i would like to see with you a topic
i want to centralize the window of a script in python
he is in usr/bin
when i use

**Group
        Name-jwmsession-/Name
        Option-centered-/Option
/Group**

in file groups does not work!

any idea?

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
hi @Israel- 
see the result of the **xwininfo -all**

https://gist.github.com/holmeslinux/8a07c33fc0d1781662020227a2212a2e

how to interpret?

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
@Israel- 
if you want to test the script

https://gist.github.com/holmeslinux/3d01840aecb43ef9a1eab0ca9ec11b0c

the idea is to centralize the window!

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@holmeslinux 
according to your output
`xwininfo: Window id: 0x2000002 "JWMSession"`
You need to use
```xml
<Group>
  <Name>JWMSession</Name>
  <Option>centered</Option>
</Group>
```
Note the **capital** JWM

**Comment by holmeslinux** [comment]
hi,
i already did that and it did not work...

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@holmeslinux I am so sorry I gave you the wrong command... you need to run
`xprop`
:smile: 
And after running it I get:
```WM_NAME(STRING) = "JWMSession"```
Are you sure you tried:
JWMSession
But really... you should do that in your application..
See here:
http://stackoverflow.com/questions/20243637/pyqt4-center-window-on-active-screen#20244839

**Comment by holmeslinux** [comment]
RESOLVED
with **self.move(QtGui.QApplication.desktop().screen().rect().center()- self.rect().center())**

thank you @Israel- 

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
@Israel- 
although the window is centered
now I'm trying to hide in the toolbar
in the groups file use the **nolist** option, but does not work

any idea?

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@holmeslinux I don't program in Python, so I don't know off the top of my head how to do it in that language... jwm-settings-manager has something similar to what you are suggesting already but it is FLTK and C++. [The image on the README.md](https://github.com/Israel-/jwm-settings-manager/blob/master/screenshots/shutdown.png?raw=true )

Did you specify JWMSession (case sensitive) AFAIK JWM reads the actual name of the window, so it should work to do this, but again, you should make your program do this rather than JWM, you should look in the documentation for PyQt4 to learn how to do this.

**Comment by holmeslinux** [comment]
@joewing 
perhaps it would be interesting to add something in groups file

**Name-exec:path/file_name-/Name**

vlw fwi, Holmes :)

**Comment by holmeslinux** [comment]
Resolved (nolist)
with **self.setWindowFlags(QtCore.Qt.Tool)**

thank you @Israel- 

vlw fwi, Holmes :)

**Comment by Israel-** [comment]
@holmeslinux Great!  glad to hear it!
