### ISSUE TITLE
The return of borders to maximized windows.

### ISSUE THREAD

**Issue by joewing** [joewing/jwm#392]
JWM currently displays no borders in the maximized directions of windows.  JWM used to not only provide borders, but would allow resizing the maximized window, effectively un-maximizing it.  The proposal here is to restore the old behavior.  There are several reasons for this:
* Windows that only resize in fixed multiples (xterm, etc.) usually have a strange edge of the window without a border.  This just looks sloppy.
* Windows can be made full-screen if screen area is a concern.
* It's nice to be able to resize such windows from any corner, providing an easy way to "push" the window to a corner of the screen.
* It simplifies the code a bit.

**Comment by joewing** [comment]
This is implemented as of snapshot 1621.

**Comment by ARR8** [comment]
Hello,
Would it be possible to add an option to restore the old behavior? Having just switched from the latest release to the development version, I find this less natural. It also reduces real estate, since not all programs support full screen. My biggest problem, though, is it is no longer possible to make edge-inward gestures on touchscreen-supported apps, something I rely on very frequently.
If it is not possible, can this be added as a group option to add certain programs to a blacklist?
Thanks in advance.

**Comment by joewing** [comment]
With the latest snapshots, it's possible to have the maximize button do fullscreen instead.  For example:
```xml
    <Mouse context="title" button="11">fullscreen</Mouse>
    <Mouse context="maximize" button="-1">fullscreen</Mouse>
```

Of course, you lose the title bar, but maybe that's what you want anyway?

**Comment by ARR8** [comment]
Thanks, that works fine for my use case, since I don't really need the title bar. However, I have some programs that send a MAXIMIZE_RESTORE signal to a window, which still uses the maximize behavior, and doesn't restore a fullscreen window. Is there a way to change that?

**Comment by ARR8** [comment]
Actually, I've noticed other problems that make this less optimal. For example, I can't access the dock (set to autohide) when a window is in fullscreen. This could probably be fixed with configuration, but other programs have undesired fullscreen behaviors that now toggle when maximizing, such as Firefox hiding its tab bar.

**Comment by ARR8** [comment]
Hello,  
  Sorry to be a bother, but is there any change in this? I have even more programs now where this behavior causes problems. It would be nice to have a configuration option for this, or even a patch I can add to the source to recompile with the old behavior. I'm sure I won't be the only one to have issues with this when the next release happens. As it is, I cannot downgrade because of other useful changes made to JWM since then; this is really my only issue with an otherwise flawless WM.

**Comment by technosaurus** [comment]
@ARR8 can you open a new issue?  I almost missed this completely since the original issue is closed.  Feel free to reference this one.
