### ISSUE TITLE
Add ~/.config/jwm/jwmrc as an alternative location for the local configuration file

### ISSUE THREAD

**Issue by romildo** [joewing/jwm#394]
Most of my file configurations are kept in `~/.config`, which allows better organization of the files on my home directory. It would be nice if `jwm` could also look for its configuration file in  `~/.config/jwm/`.

The directory for the configuration would also accommodate other files that may be included in the configuration file.

**Comment by joewing** [comment]
I like this idea.  I think making JWM search "~/.config/jwm/jwmrc" first probably makes sense as well.

**Comment by technosaurus** [comment]
not to mention that this is part of the XDG spec.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I also have some scripts to handle the autostart spec that works with jwm's startup command if you would like to include it in a contrib directory... as well as a decent (but a bit dated) config generator that I can update if desired.  Now that we have dynamic menus, I can eliminate the gtkdialog/yad dependency and do most of it using the menu system.

**Comment by joewing** [comment]
This is implemented as of snapshot 1621.

**Comment by joewing** [comment]
I'll have to think about a contrib directory with more stuff (currently it's just images).  Even if it is named "contrib", the JWM repo will end up owning it, which is good in that it gives users more options, but it adds baggage to JWM releases, etc.

**Comment by dumblob** [comment]
I'm afraid the current hard-coded path `$HOME/.config/jwm/jwmrc` is not what XDG is designed for. There is an important first step missing. Namely looking at the content of `$XDG_CONFIG_HOME` and only if it's empty use a the default value dictated by XDG, namely `$HOME/.config`.

@joewing could you please consider adding this tiny bit instead of hardcoding the fallback path?

By the way the contrib directory is not a bad idea - you could e.g. create a policy, that every item in `contrib/` would need to be a separate repository. You would then only "link" them using git submodules. If some submodule would stop being maintained, you could simply remove the "link" from the main repository (but leave some reference in the README in a section "Abandoned/unmaintained contributions").

**Comment by technosaurus** [comment]
That patch was kinda weird.  The previous method used getenv("HOME") and constructed the path, but the new one just uses $HOME in the hard coded path... does that even work?

**Comment by joewing** [comment]
It’s not really my intention to support XDG, but it’s easy enough to look at XDG_CONFIG_HOME too.  

@technosaurus The config parser is smart enough to look up environment variables, so the old way was just duplicated code.

**Comment by dimyme** [comment]
this powerful line in **~/.jwmrc** adds real value to jwm from a user's perspective. XDG is doing a good job here:

>         <Include>exec: xdgmenumaker -n -i -f jwm</Include>
