### ISSUE TITLE
The window title  is hidden when multiple call mouse binding "Button 4" or "Button 5"

### ISSUE THREAD

**Issue by roandbox** [joewing/jwm#400]
The window title is hidden when multiple call mouse binding "Button 4" or "Button 5".
The file fragment jwmrc:
```
... 
    <Mouse context="title" button="4">shade</Mouse>
    <Mouse context="title" button="5">shade</Mouse>
...
```

**Comment by joewing** [comment]
`shade` toggles the shaded state of a window (just as a `shade` key binding would).  So this is a change in behavior.  It hasn't bothered me yet, so I'm not sure it's worth restoring the old behavior, but I suppose I could be convinced otherwise.

**Comment by roandbox** [comment]
The window is not hidden but the window title is hidden.

**Comment by joewing** [comment]
Unfortunately, I don’t understand.  Your config snippet is in the default configuration, which works for me.  Please provide more information.  See also https://github.com/joewing/jwm/blob/master/CONTRIBUTING.md

**Comment by roandbox** [comment]
OS: ArchLinux
Commit: f224929e (HEAD -> jwm, tag: s1629, jwm/master)

I run jwm:
`src/jwm -f example.jwmrc`

The error screencast:
[screencast.zip](https://github.com/joewing/jwm/files/1212210/screencast.zip)

**Comment by roandbox** [comment]
I think a problem is here:
https://github.com/joewing/jwm/blob/952c0889674feb5428d54f5119b301401935817d/src/event.c#L1577-L1585

If it is remove then the error disappears.

**Comment by joewing** [comment]
Thanks for the video, very helpful!  So it turns out that if I spin my scroll wheel fast enough I can sometimes make this happen.

What's going on is that the "shade" operation causes an unmap notify, which JWM typically ignores because the window is already unmapped.  However, if you shade and then unshade fast enough, the window will get mapped again before JWM processes the unmap notify, which causes JWM to think that the window is going away.  So, to avoid that, I just made it so that JWM waits for the unmap notify event when JWM is the cause of the event.

**Comment by roandbox** [comment]
It works. Thanks for the description of cause of the problem!
