### ISSUE TITLE
Same tray on both monitors

### ISSUE THREAD

**Issue by kibojoe** [joewing/jwm#418]
hi all,
i would like to know how, in a dual-monitor, have the same tray on both monitors.

vlw fwi, Holmes :)

**Comment by joewing** [comment]
Currently, the only way to accomplish this is copy the tray and set the position such that one shows up on each screen.  Really the only complication with having the same tray in two places is that the "Dock" element can only appear once.  That's because JWM doesn't control the windows that show up in the Dock element, instead the program that creates the icon controls it and the protocol doesn't really have a way to have it control multiple windows.

**Comment by kibojoe** [comment]
ok, thank you @joewing 

vlw fwi, Holmes :)
