### ISSUE TITLE
Dead windows

### ISSUE THREAD

**Issue by bkauler** [joewing/jwm#437]
Successfully compiled 1675, however, windows are "dead".

That is, completely unresponsive to mouse actions. cannot drag, no response to right-click in title-bar, cannot resize sides. Mouse is dead as far as windows are concerned.

However, mouse still works in tray, menu, right-click menu, etc.
For example, can select "Move" from tray, and can move a window. But cannot do it from a window title-bar.

Regards,
Barry

**Comment by yetanothergeek** [comment]
Copy & paste the new mouse options / settings from /etc/system.jwmrc into your ~/.jwmrc and try again.

**Comment by joewing** [comment]
As @yetanothergeek suggested, you probably need to copy the mouse bindings.  JWM 2.4 currently requires mouse bindings to be in the configuration file (just as previous versions required key bindings).

I'm considering introducing a default configuration to avoid issues like this (#406 is another report).  See #436.

**Comment by bkauler** [comment]
Yes, that fixed it. I didn't have any <Mouse> tags. Copied them from the example jwmrc, and now the mouse works.

My comment on that, is it is not good that the mouse partly failed when there were no <Mouse> tags. It worked in the tray, but not in windows.

It should default to working as it did before these mouse tags were introduced. That's my feeling about it anyway. JWM should default to be working!

**Comment by joewing** [comment]
I tend to agree that JWM should default to working.  There is an XSLT to upgrade the configuration, but I doubt most will bother to use it and why should you worry about such details as mouse bindings if you like the defaults?

Merging #436 will make the executable bigger, but it will probably save a lot of frustration and bug reports (not to mention those who simply give up without reporting anything).

Mouse bindings for the tray is something else I’m considering making configurable.  I’m leaning toward making them configurable since I have received requests to change/add behavior.

**Comment by joewing** [comment]
Default mouse bindings are included as of snapshot 1679.
