### ISSUE TITLE
Need to set the XDG_CURRENT_DESKTOP environment variable

### ISSUE THREAD

**Issue by trlkly** [joewing/jwm#443]
This is now the standard variable to specify the window manager, and is used by some GTK programs to properly theme elements. In particular, Firefox is affected. 

My current workaround is simply to add `XDG_CURRENT_DESKTOP=JWM` to my command line for starting Firefox, based on some talk on the Puppy Linux forums about what the proper value is. 

But it would be good to have the value standardized. So please set this variable yourself.

**Comment by technosaurus** [comment]
XDG_CURRENT_DESKTOP specifies a "Desktop Environment" and jwm does not provide all aspects of such (file manager is the big one).  On the contrary jwm is often used as a replacement window manager in other desktop environments like gnome, kde, xfce, lxde, rox or unity.  If jwm were to set DE, DESKTOP_SESSION or XDG_CURRENT_DESKTOP internally, it would likely override what users have _properly_ specified in their ~/.xinitrc, so if setting XDG_CURRENT_DESKTOP=JWM means something specific to your distro or respin, please set this variable yourself (you may want ROX instead of JWM anyhow).

Keep in mind that most upstream software will not be aware of what to do when that variable is set to an unknown value like "JWM", so you will get the default setting anyhow (which is usually to use xdg-open - which IIRC, puppy typically has as a symlink to ROX-Filer instead of modifying the xdg-open script and providing the corresponding env vars)  Arch Linux has a decent set of documentation on common env vars [here](https://wiki.archlinux.org/index.php/environment_variables) but you can use the [env](https://linux.die.net/man/1/env) program to run a program like firefox with a different set of env vars (for security purposes it's good to remove any unnecessary env vars anyhow).

P.S. The Puppy Linux Forum is the last place you should look for anything regarding standards (I may be the only forum member _trying_ to get Puppy more standards compliant).  The closest thing to a standard is https://standards.freedesktop.org/ but (by its own admission) it is not a "standards organization" and the specs are becoming outdated and uncoordinated (for instance the icon naming spec and menu spec don't have a 1-1 icon-category match and the desktop entry spec does distinguish whether it can "edit" a specific MimeType)  There are also some alpha level specs at https://www.freedesktop.org/wiki/Specifications/ that are unlikely to be updated due to the difficulty of getting a new user account (Existing members are obviously not working on it)

**Comment by trlkly** [comment]
The clobbering issue has already been handled. [The proper procedure is for multiple values to be included, separated by colons.](https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1554878) This only makes sense to do if the expectation is that there will be some mixing and matching. 

The Window Manager may not be a full Desktop Environment, but it is part of one. ROX is also not a full Desktop Environment. Hence, by your logic, it should also not set a value. That leaves users of both with no value.  And that guarantees a hodgepodge of ideas. If both programs will just add themselves, then it would be the same for all applications. 

The hodgepodge is not useful at all to application developers. They will be testing for a specific value. Mozilla Firefox is one of them, and were the ones who specifically told me this was a bug in JWM. Without a value, Firefox falls back on a compatibility mode and will not draw in the titlebar. As such, the Window Manager is the part of the Desktop Environment that is important in this case.

The reference to the Puppy forums was simply to point out the value that at least some users are already using, in case the decision was made to stay consistent with existing usage. I am fully aware that a forum is not about standards.

I really don't want to get into a fight about this. If JWM will not set this variable, and Firefox will not let me work around the issue, then I will simply have to choose between the both of them. And, currently, since I can't use Chrom(ium) on my computer without problems, I would have to choose Firefox and say goodbye to JWM.

Please let's agree on a value that should be set and set it. That way I can go back to Bugzilla and tell them what that value is, so they can make the tweaks necessary to support JWM (as current support is a mess.) It seems a rather simple fix.

**Comment by technosaurus** [comment]
I understand where you are coming from, but that particular environment variable appears to be used for desktop environments  (lxde doesn't add :openbox)

The list of current environments is at: 
https://specifications.freedesktop.org/menu-spec/menu-spec-latest.html#onlyshowin-registry

Its already quite long without adding every  2 bit developer's pet combination of wm,  fm, desktop icon app, tray app, etc.  Then documenting it, raising awareness and convincing nLog(n) app developers to add and maintain 128kb worth of nested if chains into their code to support it.

I have no problem with this bug, it's the lack of sane standards.  A sane default value would be "1.0" and mean that the wm, xdg-open and friends support v1.0 or use characters to indicate support for specific functionality.  As a c programmer, I would prefer a hexadecimal string where each bit represents support for something (simpler code), but that would never fly.

Still, since jwm only provides part of this functionality and no one has agreed upon a set of characters to indicate support, it is up to the startup process to set it after verifying the other programs are available... probably in ~/.xinitrc.  Either way, I would use "1.0" and ensure that the xdg* apps are available or appropriate wrappers provided.

**Comment by Israel-D** [comment]
@trlkly I have to side with @technosaurus on this one.
JWM is not a DE, so it is up to the Desktop Environment to set this variable.  For example in ToriOS we set that variable in our startup scripts, which is how xfce does this (or at least used to do it, it may be handled by some binary now).  I wrote a script to set all the relevant variables, if they are empty.
Here are the values I set
```bash
XDG_SESSION_CLASS=user
XDG_MENU_PREFIX=lxde- # for pcmanfm to work nicely
XDG_SESSION_DESKTOP=JWM
XDG_CURRENT_DESKTOP=JWM
XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_DIRS="/usr/local/share:/usr/share"
XDG_CONFIG_DIRS="/usr/share/upstart/xdg:/etc/xdg"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share/"
SAL_USE_VCLPLUGIN=gtk
SSH_ASKPASS=torios-askpass  #zenity dialog for ssh
SUDO_ASKPASS=torios-askpass  #zenity dialog for sudo -A
```
And then finally run my autostart script and autostart modifier (if it exists) which loads things in the autostart directories, and does the things below, and I simply include in JWM via:
```xml
<StartupCommand>nice-start</StartupCommand>
```
OR it uses:
`/etc/X11/Xsession jwm`
OR it uses:
`dbus-launch --exit-with-session ck-launch-session jwm`

The startup script can be your .xinitrc (unless you use multiple DE, which I do, I test LXQt occasionally to see the progress, as well as other things), or you can use it as a default session handler.

A window manager is not a DE, and should never report itself as a DE.  Rox was (at some point, though now un-maintained) an entire Desktop Environment, which is why it is included in the specs.

Firefox has always worked for me, as well as seamonkey, chromium, chrome, qupzilla, and of course links2 😄
