### ISSUE TITLE
Discussion expanding JWM with browser libs?

### ISSUE THREAD

**Issue by vmnlopes** [joewing/jwm#46]
one of the things i like about JWM his because only loads one lib and that makes it load realy fast something that other desktops just cant do.

But for some time now am thinking how about if we could build widgets or anything we wanted  with javascrip or even style it with css (maybe an opcion in compile time for people that prefer only standard JWM or a more juicy one) this will make JWM alot more versatile (it still be faster that any other desktop) and maybe call some more devs atencion to help improve it??

**Comment by dumblob** [comment]
I personally like JWM as it is - small, not full-featured, but very fast. Any change to the current situation will require lots of code changes and testing (being it either library, or including turing complete language instead_of/in_addition_to XML, etc.) - think of at least backwards compatibility. So the question is what is Joe's ultimate goal.

If we wanted to attract people, I'm certain we need to change the XML configuration to some turing-complete language with declarative-like syntax (to allow building extremely simple GUIs for configuration while allowing distribution-makers or packagers writing their small dynamic modules) - I really liked the idea of S-expressions, because it's easy to implement, it's small and it's not dying any more (see Guix, Nix, NixOS, etc.).

Any such exposure of (currently internal) API would though also mean addition of dependency on threading library, because there would need to be possibility to run I/O operations separately from the main JWM code etc. This would mean immense refactoring of the current code. And there are lot's of other issues (the devil is in the detail). As you can see, there are only issues with such on the first sight small and neat changes.

Of course, there is this possibility to make it half-way. E.g. add S-expressions support to some XML `<script lang="joes_s_lang"></script>` tag and selectively (based on requests here on GitHub) expose some small parts of the internal JWM API without any threading support etc. This would leave things slightly simpler than described above, but would require users to be very careful.

**Comment by vmnlopes** [comment]
@joewing i tink you can close this one joe?
