### ISSUE TITLE
After compiling JWM is missing from lightdm

### ISSUE THREAD

**Issue by ghost** [joewing/jwm#466]
After compiling then log out, JWM is missing from available Xsession menu in lightdm.
[https://sparkylinux.org/images/lumina-login.png](https://sparkylinux.org/images/lumina-login.png)

How to put JWM into lightdm available xsession menu?

**Comment by number698** [comment]
Same here.

I boot to terminal and type,
startx
to enter jwm desktop, there must be a way to add jwm to lightdm menu, making startup directly go to jwm desktop ?

**Comment by yetanothergeek** [comment]
I am not a DM user but a quick google search suggests that you need to create a file named
`/usr/share/xsessions/jwm.desktop`

The file should contain something like this:

`[Desktop Entry]`
`Encoding=UTF-8`
`Name=JWM`
`Comment=A lightweight window manger for the X11 Window System`
`Exec=/usr/bin/jwm`
`TryExec=/usr/bin/jwm`
`Type=XSession`

( You might need to adjust the `Exec=` and `TryExec=` values if you installed to `/usr/local/` )

**Comment by number698** [comment]
Thanks yetanothergeek.

looked for jwm.desktop and it was already in place, and WAS also already included into the menu correctly.

turns out my problem was with /etc/lightdm.conf , it was immediately diverting the greeting menu with this entry,
greeter-session=pi-greeter
hashed it out and added,
greeter-session=lightdm-gtk-greeter
