### ISSUE TITLE
Scripting JWM tray?

### ISSUE THREAD

**Issue by acoolstraw** [joewing/jwm#528]
Hey, I'd like to add a custom script to for example display the weather or battery percentage or anything really, is there any way to do this?

Like, display whatever the script outputs somewhere here.
![image](https://user-images.githubusercontent.com/45886986/140634991-b6f3bba1-23ab-42dc-b33f-5fea0b3e03fb.png)

**Comment by joewing** [comment]
There isn't a built-in way to display arbitrary text that can update in a tray, but there is a `Swallow` component to swallow an application into the tray (see https://joewing.net/projects/jwm/config.html#trays). You should be able to use that to swallow something that shows whatever you want (like xclock, xload, etc).

**Comment by acoolstraw** [comment]
I think dynamic script output would be a pretty useful feature, that way you don't need to write an X11 application to display something

**Comment by joewing** [comment]
JWM used to implement a CPU load monitor, but I pulled that out because it brings along a lot of extra configuration and platform dependencies for a feature that most people probably wouldn't use. No functionality was lost because JWM supports `Swallow`, and JWM itself remains a smaller, simpler program. I think this is the same type of thing.

**Comment by acoolstraw** [comment]
I disagree, shell scripts bring few if any dependencies, and it's a feature a lot of people find useful for displaying things on their desktop
