### ISSUE TITLE
Dynamic menu misbehaves

### ISSUE THREAD

**Issue by bkauler** [joewing/jwm#544]
I am using 2.4.1. I created a second menu in the systray:

```
<RootMenu label="Partitions" labeled="false" height="24" onroot="2" dynamic="exec:/usr/local/ui/jwm/generate-drives-menu">
	</RootMenu>
```

The menu misbehaves very badly. For example, move the mouse pointer, the highlighted item in the menu does not move. And once the entire desktop froze, had to do a hard power-off. That 'generate-drives-menu' script generates this:

```
<JWM>
 <Program label="Unmount all">/usr/local/ui/unmount-all</Program>
 <Program label="nvme0n1p1" tooltip="Filesystem: vfat Size: 2.6GB" icon="drive48.png">/root/.pup_event/drive_nvme0n1p1/AppRun drive vfat</Program>
 <Program label="nvme0n1p2" tooltip="Filesystem: ntfs Size: 64.0GB" icon="drive48.png">/root/.pup_event/drive_nvme0n1p2/AppRun drive ntfs</Program>
 <Program label="nvme0n1p4" tooltip="Filesystem: ext4 Size: 64.0GB" icon="drive48.png">/root/.pup_event/drive_nvme0n1p4/AppRun drive ext4</Program>
 <Program label="nvme0n1p5" tooltip="Filesystem: ext4 Size: 44.0GB" icon="drive48.png">/root/.pup_event/drive_nvme0n1p5/AppRun drive ext4</Program>
 <Program label="nvme1n1p1" tooltip="Filesystem: ext4 Size: 465.7GB" icon="drive48.png">/root/.pup_event/drive_nvme1n1p1/AppRun drive ext4</Program>
</JWM>

```

However, if I change it to a static menu, with those same Program tags in it, the menu behaves properly.

At this stage it looks like I cannot use the dynamic feature, and will have to resort to running "jwm -reload".

**Comment by bkauler** [comment]
I am launching the menu from a TrayButton. As a static menu it works fine, updated with "jwm -reload":

![jwm-desk-brown-853x480](https://user-images.githubusercontent.com/4200448/153116333-2949871a-0340-4cde-a825-46fbf69a5d8f.jpg)

As a dynamic menu, it is horribly broken.

Another issue, the dynamic menu overlaps the tray.

**Comment by joewing** [comment]
Dynamic menus appear to work for me, though I suspect something with the way the timeout is implemented may be broken (I think that's the only change from 2.3 from that perspective?). I could just revert that change.

In general dynamic menus are problematic given the way they are  currently implemented.  The issue is JWM needs the menu contents before it can continue with showing the menu, and JWM currently does no other window handling during that process.  The somewhat-recently added timeout is really just a hacked solution. JWM should probably do something along the lines of starting the background task immediately upon startup, regenerating at some interval, and cache the menu so that the menu displays instantly no matter how long the task takes and even if, for some reason, the generated menu is invalid.
I think dynamic menus should probably be avoided and maybe completely removed from JWM unless they get implemented in a more robust way.

**Comment by joewing** [comment]
I just committed what might partially fix this... It was leaking file handles, which might explain some of the problems (though, that should only manifest after some amount of time when JWM runs out of file handles).

**Comment by bkauler** [comment]
Hi Joe,
Don't worry too much about fixing dynamic menus, as I have got the static menu of drive partitions working really nicely.

I have even got it so that when plugin a usb drive, the "Drives" menu pops up, using xdotool.

My objective is for EasyOS to be completely icon-free on the desktop, and it is looking good.

**Comment by bkauler** [comment]
Closing, as don't need to fix.
