### ISSUE TITLE
Strange blinking between active and inactive states

### ISSUE THREAD

**Issue by algor512** [joewing/jwm#573]
When switching between windows, something strange happens with a terminal window sometimes, see gif (I am doing nothing while recording):
![Peek 2022-06-06 11-22](https://user-images.githubusercontent.com/446041/172154366-4126642d-a722-418d-9bd6-a92137a6e5fa.gif)

(the window title bar toggles between active and inactive states while the window remains inactive, as can be seen by its transparency)

This seems to happen sometimes when I switch from the terminal window to another window.

I use JWM v2.4.2, and sakura 3.8.5 as a terminal.

**Comment by joewing** [comment]
It looks like your terminal is setting the urgency hint, which causes JWM to flash the window. I think sometimes terminals do this when they would otherwise use the bell, but don't have focus. You might be able to disable it in the terminal, though you can also disable it with the "noturgent" window group option.

**Comment by algor512** [comment]
Thank you, that was indeed the problem!
